### ISSUE TITLE
Social Auth as Feature?

### ISSUE THREAD

**Issue by CharlyJazz** [fivethreeo/react-ssr-django-jwt-docker#6]

**Comment by fivethreeo** [comment]
I will not implement it now atleast, but I will participate in design decisions if someone gives it a go ☺ Currently stuck a bit on docker swarm setup and thinking about developing a nice todo app example.

**Comment by fivethreeo** [comment]
Maybe i'll go with:

https://github.com/ice-creams/graphql-social-auth-template

**Comment by CharlyJazz** [comment]
U can avoid dependencies overload and write the views and endpoints.

Using just RAUTH

https://github.com/CharlyJazz/Flask-MVC-Template/blob/master/app/user/oauth.py

**Comment by fivethreeo** [comment]
I'll rather have dependencies than having to maintain code that end up untested and insecure. If I can be lazy I will be is my philosophy  ☺

**Comment by fivethreeo** [comment]
WIP

https://github.com/fivethreeo/django-graphql-social-auth

**Comment by fivethreeo** [comment]
Added and documented, closing :)
